# Generated by Django 4.1.1 on 2022-09-09 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='content_type',
            field=models.ForeignKey(default=7, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='user',
            name='object_id',
            field=models.PositiveIntegerField(default=None, null=True),
        ),
    ]
