# Generated by Django 4.1.1 on 2022-09-13 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('carers', '0002_alter_carer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=350)),
                ('start_date', models.CharField(max_length=25)),
                ('frequency', models.CharField(max_length=50)),
                ('treatment', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=10, verbose_name=[('new', 'New'), ('assigned', 'Assigned'), ('closed', 'Closed')])),
                ('assigned_carer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='carers.carer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('possible_carers', models.ManyToManyField(related_name='proposed_tasks', to='carers.carer')),
            ],
        ),
    ]
