# Generated by Django 4.1.1 on 2022-09-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0002_alter_carer_image'),
        ('tasks', '0004_alter_task_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_carer',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='carers.carer'),
        ),
        migrations.AlterField(
            model_name='task',
            name='possible_carers',
            field=models.ManyToManyField(blank=True, null=True, related_name='proposed_tasks', to='carers.carer'),
        ),
    ]
