# Generated by Django 4.1.1 on 2022-09-09 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=50, verbose_name=[('female', 'Female'), ('male', 'Male'), ('prefer not to say', 'Prefer Not')])),
                ('health_status', models.TextField(null=True)),
                ('allergies', models.TextField(null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
                ('emergency_contact', models.CharField(max_length=100, null=True)),
                ('em_contact_relationship', models.CharField(max_length=150, null=True)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
    ]
