# Generated by Django 4.1.1 on 2022-09-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='is_medic',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(max_length=10, verbose_name=[('female', 'Female'), ('male', 'Male'), ('other', 'Other')]),
        ),
    ]
