# Generated by Django 4.1.1 on 2022-09-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_allergies_alter_patient_contact_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_of_birth',
            field=models.CharField(default='undefined', max_length=25),
            preserve_default=False,
        ),
    ]
