# Generated by Django 4.1.1 on 2022-09-12 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=70)),
                ('image', models.CharField(blank=True, max_length=10, null=True)),
                ('bio', models.CharField(blank=True, max_length=500, null=True)),
                ('education', models.CharField(blank=True, max_length=150, null=True)),
                ('location', models.CharField(max_length=300)),
                ('is_medic', models.BooleanField(default=True)),
            ],
        ),
    ]
