# Generated by Django 4.1.1 on 2022-09-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carer',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
